seleniumhub:
  image: selenium/hub
  environment:
    - GRID_MAX_SESSION=5
    - GRID_BROWSER_TIMEOUT=100000
    - GRID_TIMEOUT=90000
    - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
  ports:
    - 4444:4444

chromenode:
  image: selenium/node-firefox-debug
  ports:
    - 6666:5900
  environment:
    - NODE_MAX_INSTANCES=10
    - NODE_MAX_SESSION=40
  links:
    - seleniumhub:hub